---
- pause:
    prompt: |
      Enter your API token (https://trailofbits.github.io/algo/cloud-hetzner.html#api-token):
    echo: false
  register: _hcloud_token
  when:
    - hcloud_token is undefined
    - lookup('env','HCLOUD_TOKEN')|length <= 0



- name: Get regions
  local_action:
    module: hcloud_datacenter_info
    api_token: "{{ hcloud_token }}"
  register: _hcloud_regions

- name: Print the regions
  debug:
    var: _hcloud_regions

- name: Set facts about the regions
  set_fact:
    hcloud_regions: "{{ _hcloud_regions | sort(attribute='location') }}"

- name: Set default region
  set_fact:
    default_region: >-
      {% for r in hcloud_regions %}
      {%- if r['location'] == "nbg1" %}{{ loop.index }}{% endif %}
      {%- endfor %}
  when:
    - hcloud_default_location is undefined
- pause:
    prompt: |
      What region should the server be located in?
        {% for r in hcloud_regions %}
        {{ loop.index }}. {{ r['location'] }}     {{ r['description'] }}
        {% endfor %}

      Enter the number of your desired region
      [{{ default_region }}]
  register: _hcloud_location
  when: hcloud_location is undefined

- name: Set additional facts
  set_fact:
    hcloud_location: >-
      {% if hcloud_location is defined %}{{ hcloud_location }}
      {%- elif _hcloud_location.user_input %}{{ hcloud_regions[_hcloud_location.user_input | int -1 ]['location'] }}
      {%- else %}{{ hcloud_regions[default_region | int - 1]['location'] }}{% endif %}